# Generated by Django 4.0.1 on 2022-02-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0002_companysystemuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='companysystemuser',
            name='num_of_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FixedAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(choices=[('Poprzedni okres obrachunkowy', 'x-3'), ('Poprzedni okres obrachunkowy', 'x-2'), ('Ostatni okres obrachunkowy', 'x-1'), ('Okres bieżący', 'x'), ('Prognoza na koniec okresu bieżącego', 'x'), ('Prognoza na koniec kolejnego roku', 'x+1'), ('Prognoza na koniec kolejnego roku', 'x+2'), ('Prognoza na koniec kolejnego roku', 'x+3')], max_length=100)),
                ('intangible_assets', models.FloatField()),
                ('tangible_assets', models.FloatField()),
                ('real_estates', models.FloatField()),
                ('tools_machines', models.FloatField()),
                ('transport', models.FloatField()),
                ('others', models.FloatField()),
                ('all_assets', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
    ]
