# Generated by Django 4.0.1 on 2022-02-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0004_alter_fixedassets_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedassets',
            name='identifier',
            field=models.CharField(default='0.0.0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser'),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='intangible_assets',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='others',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='real_estates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='time_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='tools_machines',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='transport',
            field=models.FloatField(default=0),
        ),
    ]
