# Generated by Django 4.0.1 on 2022-02-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0007_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField()),
                ('identifier', models.CharField(db_index=True, max_length=10)),
                ('own_capitals', models.FloatField(default=0)),
                ('stopped_profit_of_own_capitals', models.FloatField(default=0)),
                ('long_term_liabilities', models.FloatField(default=0)),
                ('long_term_loans_borrowings', models.FloatField(default=0)),
                ('short_term_borrowings', models.FloatField(default=0)),
                ('towards_suppliers', models.FloatField(default=0)),
                ('outdated_towards_suppliers', models.FloatField(default=0)),
                ('towards_budget', models.FloatField(default=0)),
                ('towards_zus', models.FloatField(default=0)),
                ('other_short_term_liabilities', models.FloatField(default=0)),
                ('other_liabilities', models.FloatField(default=0)),
                ('dotations', models.FloatField(default=0)),
                ('short_term_liabilities', models.FloatField()),
                ('sum_liabilities_and_provisions', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='fixedassets',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CurrentAssets',
        ),
        migrations.DeleteModel(
            name='FixedAssets',
        ),
    ]
