# Generated by Django 4.0.1 on 2022-02-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0008_liabilities_remove_fixedassets_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitsLoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField()),
                ('identifier', models.CharField(db_index=True, max_length=10)),
                ('netto_income_sum', models.FloatField()),
                ('operation_br_income', models.FloatField(default=0)),
                ('products_netto_income', models.FloatField(default=0)),
                ('goods_materials_netto_income', models.FloatField(default=0)),
                ('other_netto_income', models.FloatField(default=0)),
                ('dotations', models.FloatField(default=0)),
                ('operating_expenses_sum', models.FloatField()),
                ('depreciation', models.FloatField(default=0)),
                ('materials_energy_use', models.FloatField(default=0)),
                ('foreign_services', models.FloatField(default=0)),
                ('taxes', models.FloatField(default=0)),
                ('salaries', models.FloatField(default=0)),
                ('interesr_comissions', models.FloatField(default=0)),
                ('interests', models.FloatField(default=0)),
                ('sold_goods_values', models.FloatField(default=0)),
                ('other_expenses', models.FloatField(default=0)),
                ('supply_change_sum', models.FloatField()),
                ('supply_beg_state', models.FloatField(default=0)),
                ('supply_end_state', models.FloatField(default=0)),
                ('income_costs', models.FloatField()),
                ('gross_income', models.FloatField()),
                ('income_tax', models.FloatField(default=0)),
                ('netto_income', models.FloatField()),
                ('owner_maintnance_costs', models.FloatField()),
                ('stopped_costs', models.FloatField()),
                ('redemption_of_fixed_assets', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
    ]
