# Generated by Django 4.0.1 on 2022-02-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0009_profitsloses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitsloses',
            name='owner_maintnance_costs',
            field=models.FloatField(default=0),
        ),
    ]
