# Generated by Django 4.0.1 on 2022-02-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0010_alter_profitsloses_owner_maintnance_costs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'ordering': ['time_period']},
        ),
        migrations.AlterModelOptions(
            name='liabilities',
            options={'ordering': ['time_period']},
        ),
        migrations.AlterModelOptions(
            name='profitsloses',
            options={'ordering': ['time_period']},
        ),
        migrations.CreateModel(
            name='FullRaportBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField()),
                ('identifier', models.CharField(db_index=True, max_length=10)),
                ('money_surplus', models.FloatField(default=0)),
                ('bilans_sh_lil_ratio', models.FloatField(default=0)),
                ('financial_prop_score', models.FloatField(default=0)),
                ('financial_sc_sales_rel', models.FloatField(default=0)),
                ('supp_rev_relaton', models.FloatField(default=0)),
                ('assets_rotation', models.FloatField(default=0)),
                ('company_assessment', models.FloatField(default=0)),
                ('liquidity_ratio', models.FloatField(default=0)),
                ('return_on_assets_ratio', models.FloatField(default=0)),
                ('profitability_of_revenue_ratio', models.FloatField(default=0)),
                ('debt_ratio', models.FloatField(default=0)),
                ('company_prediction', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
            options={
                'ordering': ['time_period'],
            },
        ),
    ]
