# Generated by Django 4.0.1 on 2022-02-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0011_alter_assets_options_alter_liabilities_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
        migrations.DeleteModel(
            name='FullRaport',
        ),
    ]
