# Generated by Django 4.0.1 on 2022-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0012_finalraport_delete_fullraport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('file_path', models.FilePathField()),
            ],
        ),
    ]
