# Generated by Django 4.0.1 on 2022-02-20 21:14

import django.core.validators
from django.db import migrations, models
import economic_indicators_site.utils.year_validators


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0013_raportfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='created_at',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2010), economic_indicators_site.utils.year_validators.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='fullraportblock',
            name='created_at',
            field=models.IntegerField(default=2022),
        ),
    ]
