# Generated by Django 4.0.1 on 2022-02-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0014_assets_created_at_fullraportblock_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalraport',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='TypeOfEconomicActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('main_operation1', models.IntegerField(default=0)),
                ('main_operation1_characteristics', models.TextField(max_length=500)),
                ('main_operation1_cell1', models.IntegerField()),
                ('main_operation1_cell2', models.IntegerField()),
                ('main_operation2', models.IntegerField(default=0)),
                ('main_operation2_characteristics', models.TextField(max_length=500)),
                ('main_operation2_cell1', models.IntegerField()),
                ('main_operation2_cell2', models.IntegerField()),
                ('main_operation3', models.IntegerField(default=0)),
                ('main_operation3_characteristics', models.TextField(max_length=500)),
                ('main_operation3_cell1', models.IntegerField()),
                ('main_operation3_cell2', models.IntegerField()),
                ('main_operation4', models.IntegerField(default=0)),
                ('main_operation4_characteristics', models.TextField(max_length=500)),
                ('main_operation4_cell1', models.IntegerField()),
                ('main_operation4_cell2', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCharacteristicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=10, unique=True)),
                ('business_start_date', models.DateField()),
                ('story_subject_business', models.TextField(max_length=2000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
    ]
