# Generated by Django 4.0.1 on 2022-02-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0015_alter_finalraport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysystemuser',
            name='second_module_raports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysystemuser',
            name='third_module_raports',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CurrentPlaceOnTheMarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('receiver1', models.CharField(max_length=100)),
                ('receiver1_share', models.FloatField(default=0)),
                ('receiver2', models.CharField(max_length=100, null=True)),
                ('receiver2_share', models.FloatField(default=0, null=True)),
                ('receiver3', models.CharField(max_length=100, null=True)),
                ('receiver3_share', models.FloatField(default=0, null=True)),
                ('receiver4', models.CharField(max_length=100, null=True)),
                ('receiver4_share', models.FloatField(default=0, null=True)),
                ('clients_needs_expectations', models.TextField(max_length=2000)),
                ('company_growth_possibilities', models.TextField(max_length=2000)),
                ('company_concurency', models.TextField(max_length=2000)),
                ('company_competitive_advantages', models.TextField(max_length=2000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantOfferOperationIncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=10)),
                ('goods_offered_now1', models.CharField(max_length=100)),
                ('income_penultimate_year_now1', models.FloatField(default=0)),
                ('income_last_year_now1', models.FloatField(default=0)),
                ('income_current_year_now1', models.FloatField(default=0)),
                ('notes1', models.CharField(max_length=150, null=True)),
                ('income_penultimate_year_now2', models.FloatField(default=0)),
                ('income_last_year_now2', models.FloatField(default=0)),
                ('income_current_year_now2', models.FloatField(default=0)),
                ('notes2', models.CharField(max_length=150, null=True)),
                ('income_penultimate_year_now3', models.FloatField(default=0)),
                ('income_last_year_now3', models.FloatField(default=0)),
                ('income_current_year_now3', models.FloatField(default=0)),
                ('notes3', models.CharField(max_length=150, null=True)),
                ('income_penultimate_year_stopped1', models.FloatField(default=0)),
                ('income_last_year_stopped1', models.FloatField(default=0)),
                ('income_current_year_stopped1', models.FloatField(default=0)),
                ('stopped_notes1', models.CharField(max_length=150, null=True)),
                ('income_penultimate_year_stopped2', models.FloatField(default=0)),
                ('income_last_year_stopped2', models.FloatField(default=0)),
                ('income_current_year_stopped2', models.FloatField(default=0)),
                ('stopped_notes2', models.CharField(max_length=150, null=True)),
                ('income_penultimate_year_stopped3', models.FloatField(default=0)),
                ('income_last_year_stopped3', models.FloatField(default=0)),
                ('income_current_year_stopped3', models.FloatField(default=0)),
                ('stopped_notes3', models.CharField(max_length=150, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
        ),
    ]
