# Generated by Django 4.0.1 on 2022-02-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0016_companysystemuser_second_module_raports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMarketAnalisisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crated_at', models.DateField(auto_now_add=True)),
                ('identifier', models.CharField(db_index=True, max_length=10)),
                ('applicant_offer_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.applicantofferoperationincomemodel')),
                ('characteristic_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.businesscharacteristicmodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
                ('operation_type_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.typeofeconomicactivitymodel')),
                ('place_on_market_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.currentplaceonthemarketmodel')),
            ],
        ),
    ]
