# Generated by Django 4.0.1 on 2022-02-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0017_fullmarketanalisismodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullmarketanalisismodel',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver1_share',
            field=models.FloatField(default=100),
        ),
    ]
