# Generated by Django 4.0.1 on 2022-02-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0018_rename_crated_at_fullmarketanalisismodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='notes1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='notes2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='notes3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='stopped_notes1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='stopped_notes2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='stopped_notes3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver2_share',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver3_share',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentplaceonthemarketmodel',
            name='receiver4_share',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
