# Generated by Django 4.0.1 on 2022-02-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0019_alter_applicantofferoperationincomemodel_notes1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullMarketAnalisisModel',
            new_name='FullMarketAnalysisModel',
        ),
    ]
