# Generated by Django 4.0.1 on 2022-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0021_applicantofferoperationincomemodel_goods_offered_now2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='notes1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='notes2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='notes3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='stopped_notes1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='stopped_notes2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantofferoperationincomemodel',
            name='stopped_notes3',
            field=models.CharField(default='', max_length=150),
        ),
    ]
