# Generated by Django 4.0.1 on 2022-02-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0022_alter_applicantofferoperationincomemodel_notes1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullmarketanalysismodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='fullmarketanalysismodel',
            name='file_path',
            field=models.FilePathField(null=True),
        ),
    ]
