# Generated by Django 4.0.1 on 2022-02-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0024_alter_applicantofferoperationincomemodel_notes1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdModuleMainComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.companysystemuser')),
            ],
            options={
                'ordering': ['-type'],
            },
        ),
        migrations.CreateModel(
            name='ThirdModuleTableComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('h', 'Godzina'), ('d', 'Dzień'), ('w', 'Tydzień'), ('m', 'Miesiąc')], max_length=10)),
                ('duration', models.IntegerField()),
                ('main_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_indicators_site.thirdmodulemaincomponentmodel')),
            ],
        ),
    ]
