# Generated by Django 4.0.1 on 2022-02-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economic_indicators_site', '0026_thirdmoduleraport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdmodulemaincomponentmodel',
            options={'ordering': ['type']},
        ),
    ]
